### ISSUE TITLE
[Feat] Popup CardView Detail 작업

### ISSUE THREAD

**Issue by JJunghyunY** [DeveloperAcademy-POSTECH/MC2-Team13-Ddojeon#12]
---
# Description
 - Popup Animation및 Lottie 변경

---

# Tasks
- [x] Import Lottie
- [x] Lottie CardView
- [x] CardView Gradient
- [x] Gradient를 위한 ColorAsset 추가
- [x] Edit Coredata (몇번째 데이터(order) attribute 추가 및 add 함수 수정)
- [x] CardView Present Lottie로 변경
- [x] CardFullScreenView Image 수정
- [x] shake effect 제거
- [x] 나가기버튼으로 MainView 되돌아가기

 # ETC
데이터 삭제시 order 초기화 하는 부분은 나중에

**Comment by JJunghyunY** [comment]
(Coredata) group value 올리는것도 다음에 해야함!
