### ISSUE TITLE
[Feat] 메인 화면 칭찬 저금통 개발

### ISSUE THREAD

**Issue by SeBin-Kwon** [DeveloperAcademy-POSTECH/MC2-Team13-Ddojeon#15]
---
# Description

 - 칭찬 저금통 디테일 개발

---

# Tasks
- [x] 칭찬이 하나도 없을 경우 칭찬 저금통 터치 안되게 하기
- [x] 만기일시 개봉할 것인지 얼럿 추가
- [x] 만기일날 통이 흔들리는 애니메이션
- [x] 칭찬돌 이미지 추가
- [x] 칭찬 저금통 기기별 해상도 최적화 구현
- [x] 칭찬 쓰기 버튼 시간 기준 활성화/비활성화 구현

 # ETC
...
