### ISSUE TITLE
[Feat] 칭찬쓰기 화면 개발

### ISSUE THREAD

**Issue by chaekie** [DeveloperAcademy-POSTECH/MC2-Team13-Ddojeon#2]
---
# Description

 - 칭찬쓰기 화면 (모달 제외) 구현

---

# Tasks
- [x] 칭찬요정팁 버튼 가로스크롤
- [x] 칭찬쓰기
- [x] 작성 중 뒤로 가기 시 내용 유실 알림창
- [x] 저장 후 메인화면으로 이동

 # ETC
...
