### ISSUE TITLE
[Feat] 아카이브 페이지 개발

### ISSUE THREAD

**Issue by bravej1x4** [DeveloperAcademy-POSTECH/MC2-Team13-Ddojeon#3]
---
# Description

 - 아카이브 페이지 리스트 뷰 개발 관련 내용입니다.

---

# Tasks
- [x] 칭찬 아카이빙 리스트 토글
- [x] 리스트 편집 모드
- [x] 리스트 선택 삭제
- [x] ~~리스트 전체 삭제~~

 # ETC
...
