### ISSUE TITLE
[Feat] 온보딩 화면 개발

### ISSUE THREAD

**Issue by OLING99** [DeveloperAcademy-POSTECH/MC2-Team13-Ddojeon#4]
---
# Description

 - 온보딩 아직 디자인 롯띠랑 칭구칭구

---

# Tasks
- [x] 온보딩 화면 '다음' 버튼
- [x] 온보딩 화면 '이전' 버튼
- [x] 온보딩 화면 칭찬 예시 적는 텍스트 화면
- [x] 온보딩 화면에 로띠 적용

 # ETC
...

**Comment by JJunghyunY** [comment]
메인 브랜치 머지 완료
