### ISSUE TITLE
[Fix] 메인 화면 초기화 로직 변경

### ISSUE THREAD

**Issue by SeBin-Kwon** [DeveloperAcademy-POSTECH/MC2-Team13-Ddojeon#46]
---
# Description

 - 칭찬이 하나 추가되었음에도 emptyState 이미지가 나오는 에러
 - 주간 칭찬 카드가 나오자마자 메인 화면이 초기화 되는 것이 아닌 주간 칭찬 카드를 닫았을 때 메인이 초기화 되도록 변경
 - 메인화면 디자인 레이아웃 디테일 수정

---

# Tasks
- [x] emptyState 이미지 에러 수정
- [ ] CardFullScreenView가 닫힐 때 메인 화면 초기화
- [x] 메인화면 디자인 디테일 수정

 # ETC
...
