### ISSUE TITLE
온보딩페이지 수정

### ISSUE THREAD

**Issue by SeBin-Kwon** [DeveloperAcademy-POSTECH/MC2-Team13-Ddojeon#53]
---
# Description

 - 온보딩 부분 삭제
 - 스킵 버튼 추가
 - 스와이프는 그대로 살리기
 - [디자인] 칭찬팁 설명하는 칭찬작성 온보딩 화면 설명 로띠 디자인 변경

---

# Tasks
- [x] 온보딩 부분 삭제
- [x] 스킵 버튼 추가
- [x] 스와이프는 그대로 살리기

 # ETC
...
