### ISSUE TITLE
메인화면 요일 설정

### ISSUE THREAD

**Issue by SeBin-Kwon** [DeveloperAcademy-POSTECH/MC2-Team13-Ddojeon#58]
---
# Description

 - 상자 안 3D처럼 라인 추가
 - 디폴트로 오늘 요일로 자동 설정 (기능은 없음)
 - 첫 칭찬이 끝나면 “축하카드”를 통해 요일을 바꿀 수 있음을 알려주기
 - 축하카드에서 확인 대신 "요일 설정" 버튼으로 수정

---

# Tasks
- [x] 메인화면 첫 진입시 현재 요일로 기본 설정
- [x] 첫 칭찬을 하기 전엔 요일 설정 버튼 disable
- [x] 첫 칭찬 축하카드에서 요일설정 할 수 있게 변경
- [x] 현재 요일로 설정하면 당장 오늘은 열 수 없게 막기
- [x] 상자 열고 나서 칭찬 작성했을 때 또 상자 열 수 없게 막기

 # ETC
...
