### ISSUE TITLE
[Feat] 메인 화면 개발

### ISSUE THREAD

**Issue by SeBin-Kwon** [DeveloperAcademy-POSTECH/MC2-Team13-Ddojeon#6]
---
# Description

 - 칭구 메인 화면

---

# Tasks
- [x] 요일 설정
- [x] 칭찬 개수 만큼 쌓이는 박스
- [x] 중도 해지 기능
- [x] 만기일에 저금통 깨서 보는 기능

 # ETC
...
