### ISSUE TITLE
디자인 QA

### ISSUE THREAD

**Issue by chaekie** [DeveloperAcademy-POSTECH/MC2-Team13-Ddojeon#76]
# Description
온보딩과 칭찬작성 화면 내 디자인 qa를 반영합니다.

# Tasks
- [x] 온보딩 칭찬팁 화면(onboarding_4) 설명 디자인 맞게 수정
- [x] 칭찬 작성화면 내 sheet : 폰트 웨이트 + 행간 조정
- [ ] ~~ios17에서 칭찬쓰기 작성팁 모달이 키보드에 맞게 올라오는지 확인~~
-> ios17(Beta)은 Xcode 15(Beta)에서만 확인 가능해 현재로서는 버그 픽스가 힘듦
- [x] 칭찬하기 모달 시트의 드래그 인디케이터 없애기
- [x] 칭찬하기 화면에서 키보드 간혹 안뜨는 버그
