### ISSUE TITLE
[Feat] 메인 화면 디테일 개발

### ISSUE THREAD

**Issue by SeBin-Kwon** [DeveloperAcademy-POSTECH/MC2-Team13-Ddojeon#9]
---
# Description

 - 메인 화면에 들어갈 기능들 추가

---

# Tasks
- [x] 이미지 랜덤 형식으로 변경
- [x] 요일 변경 시 얼럿
- [x] 중도해지 기능 추가
- [x] 아카이브 버튼

 # ETC
...
